version: '3.9'

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  django:
    restart: always
    build:
      context: ./src #docker file here
    env_file:
      - ./.env.dev
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
    command: ["python3", "./mail_sender/manage.py", "runserver", "0.0.0.0:8000"]


  worker:
    restart: always
    build:
      context: ./src
    volumes:
      - ./src/:/usr/src/app/
    depends_on:
      - redis
    env_file:
      - ./.env.dev
    command: ["celery", "--workdir=./mail_sender", "-A", "mail_sender", "worker", "-l", "info"]

  beat:
    restart: always
    build:
      context: ./src
    depends_on:
      - worker
      - redis
    volumes:
      - ./src/:/usr/src/app/
    env_file:
      - ./.env.dev
    command: ["celery", "--workdir=./mail_sender", "-A", "mail_sender", "beat", "-l", "info", "-S", "django"]

#  flower:
#    restart: always
#    build:
#      context: ./src
#    command: ["celery", "--workdir=./mail_sender", "-A", "mail_sender", "flower", "--port=5001"]
#    ports:
#      - "5001:5001"
#    env_file:
#      - ./.env.dev

  pgdb:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: pgdb
    ports:
      - "5432:5432"
    volumes:
      - pgdbdata-new:/var/lib/postgresql/data/

  migration:
    build:
      context: ./src
    command: python ./mail_sender/manage.py migrate --noinput
    depends_on:
      - pgdb
    env_file:
      - ./.env.dev
volumes:
  pgdbdata-new:
