version: '3.9'

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  django:
    restart: always
    build:
      context: ./webapp #docker file here
    env_file:
      - ./.env.dev
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
#    environment:
#      DEBUG: "False"
#      SECRET_KEY: "dasdweujf2iu3129iOJU@213"
#      DJANGO_ALLOWED_HOSTS: "localhost 127.0.0.1 [::1]"
#      SQL_ENGINE: "django.db.backends.postgresql_psycopg2"
#      SQL_DATABASE: "postgres"
#      SQL_USER: "postgres"
#      SQL_PASSWORD: "postgres"
#      SQL_HOST: "pgdb"
#      SQL_PORT: 5432
    command: ["python3", "./mail_sender/manage.py", "runserver", "0.0.0.0:8000"]


  worker:
    restart: always
    build:
      context: ./webapp
    volumes:
      - ./webapp/:/usr/src/app/
    depends_on:
      - redis
    env_file:
      - ./.env.dev
    command: ["celery", "--workdir=./mail_sender", "-A", "mail_sender", "worker", "-l", "info"]

  beat:
    restart: always
    build:
      context: ./webapp
    depends_on:
      - worker
      - redis
    volumes:
      - ./webapp/:/usr/src/app/
    env_file:
      - ./.env.dev
    command: ["celery", "--workdir=./mail_sender", "-A", "mail_sender", "beat", "-l", "info", "-S", "django"]

#  flower:
#    restart: always
#    build:
#      context: ./webapp
#    command: ["celery", "--workdir=./mail_sender", "-A", "mail_sender", "flower", "--port=5001"]
#    ports:
#      - "5001:5001"
#    env_file:
#      - ./.env.dev

  pgdb:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: pgdb
    ports:
      - "5432:5432"
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

  migration:
    build:
      context: ./webapp
    command: python ./mail_sender/manage.py migrate --noinput
    depends_on:
      - pgdb
    env_file:
      - ./.env.dev
volumes:
  pgdbdata:
