# Generated by Django 4.2.10 on 2024-02-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_taskcore_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcore',
            name='emails',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskcore',
            name='message',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskcore',
            name='number_of_valid_emails',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskcore',
            name='subject',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
