# Generated by Django 4.2.10 on 2024-02-15 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_results', '0011_taskresult_periodic_task_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_alter_taskhistory_task_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails', models.JSONField()),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('task_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_celery_results.taskresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='singleemail',
            name='user',
        ),
        migrations.DeleteModel(
            name='MassEmail',
        ),
        migrations.DeleteModel(
            name='SingleEmail',
        ),
    ]
