# Generated by Django 4.2.10 on 2024-02-15 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_taskcore_emails_taskcore_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails', models.JSONField()),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('task_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.taskcore')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
