# Generated by Django 4.2.10 on 2024-02-17 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_celery_results', '0011_taskresult_periodic_task_name'),
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('core', '0012_remove_taskcore_number_of_valid_emails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailhistory',
            options={'verbose_name': 'History of emails', 'verbose_name_plural': 'History of emails'},
        ),
        migrations.AlterModelOptions(
            name='taskcore',
            options={'verbose_name': 'Task management', 'verbose_name_plural': 'Task management'},
        ),
        migrations.AlterModelOptions(
            name='taskhistory',
            options={'verbose_name': 'History of emails sent by tasks', 'verbose_name_plural': 'History of emails sent by tasks'},
        ),
        migrations.AlterField(
            model_name='emailhistory',
            name='emails',
            field=models.JSONField(verbose_name='Email(s)'),
        ),
        migrations.AlterField(
            model_name='emailhistory',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='emailhistory',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='emailhistory',
            name='task_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_celery_results.taskresult', verbose_name='Task result'),
        ),
        migrations.AlterField(
            model_name='emailhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='taskcore',
            name='emails',
            field=models.JSONField(verbose_name='Email(s)'),
        ),
        migrations.AlterField(
            model_name='taskcore',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='taskcore',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='taskcore',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask', verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='taskcore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='emails',
            field=models.JSONField(verbose_name='Emails'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='task_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_celery_results.taskresult', verbose_name='Task result'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
