# Generated by Django 4.2.10 on 2024-02-17 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_emailhistory_options_alter_taskcore_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails', models.JSONField(verbose_name='Email(s)')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
            ],
        ),
        migrations.RemoveField(
            model_name='emailhistory',
            name='emails',
        ),
        migrations.RemoveField(
            model_name='emailhistory',
            name='message',
        ),
        migrations.RemoveField(
            model_name='emailhistory',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='taskcore',
            name='emails',
        ),
        migrations.RemoveField(
            model_name='taskcore',
            name='message',
        ),
        migrations.RemoveField(
            model_name='taskcore',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='taskhistory',
            name='emails',
        ),
        migrations.RemoveField(
            model_name='taskhistory',
            name='message',
        ),
        migrations.RemoveField(
            model_name='taskhistory',
            name='subject',
        ),
        migrations.AddField(
            model_name='emailhistory',
            name='email_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.emaildata', verbose_name='Email(s)'),
        ),
        migrations.AddField(
            model_name='taskcore',
            name='email_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.emaildata', verbose_name='Email(s)'),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='email_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.emaildata', verbose_name='Email(s)'),
        ),
    ]
